# Generated by Django 3.2.5 on 2021-08-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='password',
            field=models.CharField(default='None', max_length=10, null=True),
        ),
    ]
